package by.htp.it.controller;

public enum CommandName {
	
	REGISTRATION_PAGE, 
	AUTHORIZATION_PAGE, 
	REGISTRATION_NEW_USER, 
	UNKNOWN_COMMAND, 
	AUTHORIZATION_USER,
	GO_TO_MAIN_PAGE, 
	CHANGE_LOCAL
	
}
