package by.htp.it.controller;

public enum CommandName {
	
	REGISTRATION_PAGE, 
	AUTHORIZATION_PAGE, 
	REGISTRATION_NEW_USER, 
	UNKNOWN_COMMAND, 
	AUTHORIZATION_USER,
	GO_TO_MAIN_PAGE,
	GO_TO_ADD_NEWS_PAGE,
	AFTER_AUTHORIZATION,
	CHANGE_LOCAL,
	ADD_NEWS,
	GO_TO_EDIT_NEWS_PAGE,
	EXIT,
	READ_NEWS,
	ADD_TO_FAVORITES,
	DELETE_FROM_FAVORITES,
	ADD_COMMENT,
	OPEN_PROFILE,
	VIEW_FAVORITE_NEWS,
	GO_TO_OFFER_NEWS_PAGE,
	VIEW_MY_OFFERED_NEWS,
	VIEW_OFFERED_NEWS,
	CHANGE_PASSWORD,
	READ_ALL_NEWS,
	GO_TO_ALL_NEWS_PAGE,
	GO_TO_CHANGE_PASSWORD_PAGE,
	DELETE_NEWS,
	EDIT_NEWS,
	GO_TO_PUBLISH,
	DO_NOT_PUBLISH,
	GO_TO_CHECK_OFFERED_NEWS_PAGE
	
}
