package by.htp.it.controller;

public enum CommandName {
	
	REGISTRATION_PAGE, 
	AUTHORIZATION_PAGE, 
	REGISTRATION_NEW_USER, 
	UNKNOWN_COMMAND, 
	AUTHORIZATION_USER, 
	GO_TO_MAIN_PAGE, 
	ADD_NEWS,
	GO_TO_ADD_NEWS_PAGE,
	DELETE_NEWS, 
	EDIT_NEWS,
	GO_TO_EDIT_NEWS_PAGE,
	VIEW_OFFERED_NEWS, 
	DO_NOT_PUBLISH,
	GO_TO_CHECK_OFFERED_NEWS_PAGE,
	GO_TO_PUBLISH,
	AFTER_AUTHORIZATION, 
	CHANGE_LOCAL,
	READ_NEWS,
	ADD_TO_FAVORITES,
	DELETE_FROM_FAVORITES,
	READ_ALL_NEWS,
	OPEN_PROFILE, 
	VIEW_FAVORITE_NEWS, 
	ADD_COMMENT,
	OFFER_NEWS, 
	GO_TO_OFFER_NEWS_PAGE,
	VIEW_MY_OFFERED_NEWS,
	GO_TO_CHANGE_PASSWORD_PAGE, 
	CHANGE_PASSWORD, 
	EXIT, 
	GO_TO_ALL_NEWS_PAGE
	
}
